name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch (change if your default branch is different)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Node.js (Optional if you have a build step, otherwise skip)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version here (you can skip if not needed)

    - name: Install dependencies (Optional if you have dependencies)
      run: npm install  # Only if you need dependencies, such as for a React app or build step

    - name: Build the project (Optional, remove if not needed)
      run: npm run build  # Only if you need a build step like bundling or minification

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.1.1
      with:
        branch: gh-pages  # The branch you want to deploy to (usually 'gh-pages')
        folder: .  # The folder to deploy (use '.' if you're deploying the root files like index.html, about.html)
        token: ${{ secrets.GITHUB_TOKEN }}  # This allows the action to push to GitHub Pages

#
